### ISSUE TITLE
Code Changes Not Reflected In Gazebo Simulation

### ISSUE THREAD

**Issue by abentleym** [BCLab-UNM/Swarmathon-ROS#19] opened 2016-02-14 21:06 UTC
My team and I tried modifying some of the source code files and running them in Gazebo and the Virtual Simulator, but none of the code changes are reflected in them. We tried introducing fatal errors in the source code and even removing entire files, but the simulation still runs as if nothing had changed.
We would edit our code in Emacs or QtCreator, close down Gazebo and the terminal, and restart and rerun everything.

**Comment by mike-matera** [comment] 2016-02-15 04:30
Hi, 

Did you run the command;

$ catkin_make 

No source code changes will be reflected until you recompile your source into object code. Here's what I usually do when I run the simulator:

$ catkin_make && ./run.sh 

This runs the compiler and only executes the simulator if the compiler succeeded. Check this tutorial out: 

http://wiki.ros.org/ROS/Tutorials/BuildingPackages

Make sure to select the "catkin" version of the tutorial.

Cheers
./m

**Comment by TGlenn2012** [comment] 2016-02-15 23:08
Hello,

When I type the command above, I get the following error

terrell@terrell-N56JN:~/rover_workspace$ catkin_make && ./run.sh
Base path: /home/terrell/rover_workspace
Source space: /home/terrell/rover_workspace/src
Build space: /home/terrell/rover_workspace/build
The build space at '/home/terrell/rover_workspace/build' was previously built by 'catkin build'. Please remove the build space or pick a different build space.

Could you please provide some advisement for me so that I may move forward?

**Comment by mike-matera** [comment] 2016-02-15 23:44
First, try to run this command: 

$ catkin_make clean

If that errors out you can safely erase the build directory with this command:

$ rm -rf ~/rover_workspace/build 

After that try to build with catkin:

$ catkin_make 

Cheers
./m

**Comment by ThomasF-Brandt** [comment] 2016-02-16 18:57
When I try running the catkin_make command, I get an error that reads 

Invoking "make -j2 -l2" failed

what does that mean?

**Comment by jhecker** [comment] 2016-02-17 20:52
You should check the debug output above the error line for more information. The compiler should tell you exactly where the problem is within the Swarmathon-ROS code base, which should help you to remedy your bug.

I'm closing this issue for now. If you encounter additional minor issues in the future, please post them to the [Swarmathon Q&A Forum](http://nasaswarmathon.com/qa-forum/).

**Closed by jhecker** 2016-02-17 20:52 UTC
